### ISSUE TITLE
EVERYTHING IS BROKEN

### ISSUE THREAD

**Issue by WkSavage** [WkSavage/NSS-SpaghettiCode#2]
im slowly fixing this. when this is closed it means that i was able to successfully start a server and perform tasks with the code i changed

**Comment by WkSavage** [comment]
UPDATE, 97 ERRORS, ALMOST THERE

**Comment by BlueNexus** [comment]
Make a do-not-merge pull request into Sshado/master. When the travis CI runs, I'll be able to see the errors, and help fix them.

**Comment by wksavageschool** [comment]
All errors have been fixed. As of this point (when I get home)I will begin testing. After the system is confirmed to work I will begin tweaking things. When I get Home I'll merge pull this with the master

**Comment by BlueNexus** [comment]
As a note, you were going to be working on genetics, correct? If so, it might be best to use a plasmid system, as in real life. I highly recommend doing some research into genetic engineering. If this's the wrong person, just tell this to them.
